### ISSUE TITLE
Game was update , it seemed that I cannot use it...

### ISSUE THREAD

**Issue by sumover** [FINDarkside/TLD-Save-Editor#6] opened 2019-05-10 07:29 UTC

**Comment by agrunwald82** [comment] 2019-05-10 12:37
Yes. The sprains system was overhauled and new inventory items were added, therefore any saves made after the 2019 update will not work in the 2018 Save Editor.

**Comment by FINDarkside** [comment] 2019-05-12 01:03
Duplicate of #5

**Closed by FINDarkside** 2019-05-12 01:03 UTC
